In [1]:
# ques1  Create two 3×3 matrices using the random function in Numpy and perform the following operations.
# è Product (prod)
# è Multiplication (multiply)
# è Dot Product (dot)
import numpy as np
from numpy import random

x = random.rand(3, 3)
y = random.rand(3, 3)
print("Matrix x is",x)
print("Matrix y is",y)
res=np.multiply(x,y)
print("The multiplication of matrix using multiply is ",res)
res=np.prod([x,y])
print(res)
res=np.dot(x,y)
print("The product of matrix using dot is",res)


# ques2 Perform the following set operations using the Numpy functions.
# è Union
# è Intersection
# è Set difference
# è XOR

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

res = np.union1d(arr1, arr2)
print("\n\n\nThe union of two arr1 and arr2",res)

res = np.intersect1d(arr1, arr2, assume_unique=True)
print("\n\n\nThe intersection of two arr1 and arr2",res)

res = np.setdiff1d(arr1, arr2, assume_unique=True)
print("\n\n\nThe set difference of two arr1 and arr2",res)

res = np.setxor1d(arr1,arr2, assume_unique=True)
print("The set difference of two arr1 and arr2",res)
# ques3Q3. Create a 1D array using Random function and perform the following operations.
# è Cumulative sum
# è Cumulative Product
# è Discrete difference (with n=3)
# è Find the unique elements from the array
res = np.cumsum([arr1,arr2])
print("\n\n\nCumulative sum",res)
res = np.cumprod([arr1,arr2])
print("\n\n\nCumulative product",res)
res = np.diff(arr1)
print("\n\n\nCumulative difference",res)

res = np.unique(arr1)
print("\n\n\nUnique element of the array",res)

# ques4 Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())


x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print("zip od array x and y ",z)

x = [1, 2, 3, 4]
y = [5,6,7,8]
res = np.add(x, y)
print("addition of element of the 2 arrays",res)


def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print("user defined function ",myadd([1, 2, 3, 4], [5, 6, 7, 8]))

# Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print("LCM of num1 and num2",x)


arr = np.array([3, 6, 9])
x = np.gcd.reduce(arr)
print("GCD of the elements of the array",x)

Matrix x is [[0.76035887 0.30260135 0.4543779 ]
 [0.14995944 0.15636122 0.58058653]
 [0.39082246 0.45207694 0.03845346]]
Matrix y is [[0.71900874 0.94805276 0.42840982]
 [0.73831364 0.87165671 0.95588951]
 [0.21602363 0.56933411 0.79643306]]
The multiplication of matrix using multiply is  [[0.54670467 0.28688204 0.19465996]
 [0.1107171  0.13629331 0.55497657]
 [0.08442689 0.25738282 0.03062561]]
1.7015380451862219e-07
The product of matrix using dot is [[0.86827574 1.24331766 0.97688024]
 [0.34868618 0.60901048 0.67610646]
 [0.62308619 0.78646907 0.63019339]]



The union of two arr1 and arr2 [1 2 3 4 5 6]



The intersection of two arr1 and arr2 [3 4]



The set difference of two arr1 and arr2 [1 2]
The set difference of two arr1 and arr2 [1 2 5 6]



Cumulative sum [ 1  3  6 10 13 17 22 28]



Cumulative product [   1    2    6   24   72  288 1440 8640]



Cumulative difference [1 1 1]



Unique element of the array [1 2 3 4]
zip od array x and y  [5, 7, 9, 11]
addition of element of